### PR TITLE
Fix #277: ExplicitJobPermissionsRule for redundant workflow permissions

### LINKED ISSUE #277: False negative ExplicitJobPermissions when both workflow and job permissions are defined
### Version

ghlint 0.5.0

### Reproduction steps

1. File `.github/workflows/x.yml` with the following content:
    ```yaml
    name: "Onboard GitHub repository to Renovate"
    
    on: push
    permissions:
      pull-requests: write
      contents: write
    jobs:
      job:
        runs-on: ubuntu-latest
        permissions:
          pull-requests: write
          contents: write
        steps:
          - uses: actions/checkout@v4
    ```

2. Run `ghlint` with the following arguments:
   ```shell
   ghlint --console .github/workflows/x.yml
   ```

### Expected behavior

ExplicitJobPermissions because the workflow ones are redundant.

### Actual behavior

Nothing.

### Additional Context

ref: platform-52

### PR DESCRIPTION
**Pull request by timsearle**
Resolves #277

### CODE REVIEW

File: modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/ExplicitJobPermissionsRule.kt [hunk 1]
```diff
@@ -21,6 +23,21 @@ public class ExplicitJobPermissionsRule : VisitorRule, WorkflowVisitor {
 		if (job.permissions == null && job.parent.permissions != null) {
 			reporting.report(ExplicitJobPermissions, job) { "${it} should have explicit permissions." }
 		}
+		if (job.permissions != null &&
+				job.parent.permissions != null &&
+				containsDuplicatePermissions(job.parent.permissions.orEmpty(), job.permissions.orEmpty())
+		) {
+			reporting.report(RedundantWorkflowPermissions, job) { "$it should have explicit permissions." }
+		}
```
Comment (TWiStErRob) [inline modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/ExplicitJobPermissionsRule.kt:31]: I think this might be enough to cover the issue, and give a good recommendation / description:

```suggestion
		if (job.permissions != null && job.parent.permissions != null) {
			reporting.report(ExplicitJobPermissions, job.parent) { "${it} has redundant permissions." }
		}
```
Note: the 2nd parameter is the workflow.

This means we don't need a new Issue, nor checking for duplicate permissions explicitly.

`ExplicitJobPermissions` "forces" a best practice of declaring on job level **only** (maybe the title needs updating appending this "only"?). This is just a variant of the same issue. So the above suggestion + a new non-compliant example with explanation should be enough. For example having the workflow-level permissions block makes maintenance risky, because a new job added to the file will have more permissions than necessary.

The recommendation "Move the permissions declaration from the workflow level to the job level." covers the redundant case too, because if you cut it from the job level and paste it over the job level, then you have essentially just "removed" the redundant bit.

---

Otherwise we might go down the rabbit hole of super-set and sub-set of permissions, permissions elevation and restriction, and cross-job + workflow permissions checking. For example:
```yaml
permissions:
  contents: read
  pull-request: write
  actions: write
  checks: write
jobs:
  job1:
    permissions:
      contents: write
      pull-request: write
      checks: read
  job2:
    permissions:
      contents: read
      pull-request: read
       # ... vulnerable script can execute any workflow_dispatch in the repo
  job3:
     # no permissions
     run: |
       # ... vulnerable script that has RCE can create a PR, and potentially even merge
       gh workflow run ...
```
Compare this to when the workflow-level permission is flagged as `ExplicitJobPermissions`, which should make the user realize that job3 needs `actions: write` and nothing else.

By enforcing job level only explicitness is a win, and as a gracious side effect those complex permission-checking rules may not need writing at all in the future.

Comment (timsearle) [reply modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/ExplicitJobPermissionsRule.kt]: 5a31c6e05ad0c1a687acc4f223dd80715ef16f46
